#Somatic and Germline Frequencies on Single Histogram
library(ggplot2)
TrueHetFiltAlleleFreq=read.delim("C:/Users/mjuswilc/OneDrive - tu-dortmund.de/Documents/TU-Dortmund/GreatTits/Projects/Deconvolution/UltimateDeconvolution/HeterozygoteSimulation/Data/FiltAlleleFreq/Summary/sbS100X-SNV-TrueHetAlleleFreq.txt", header=TRUE)
TrueHetFiltAlleleFreq$NullAltFiltAlleleFreq=rbinom(length(TrueHetFiltAlleleFreq$AlleleFreq), size=round((TrueHetFiltAlleleFreq$Depth/2)+0.5), prob=mean(TrueHetFiltAlleleFreq$AlleleFreq))/round((TrueHetFiltAlleleFreq$Depth/2)+0.5)
TrueHetFiltAlleleFreq$SomaticAlleleFreq=rbinom(length(TrueHetFiltAlleleFreq$AlleleFreq), size=round((TrueHetFiltAlleleFreq$Depth/2)+0.5), prob=0.09292727)/round((TrueHetFiltAlleleFreq$Depth/2)+0.5)

HistogramHysteria=data.frame(Estimate=c(rep("Germline", dim(TrueHetFiltAlleleFreq)[1]), rep("Est-Germline", dim(TrueHetFiltAlleleFreq)[1]), rep("Est-Somatic", dim(TrueHetFiltAlleleFreq)[1])), AlleleFrequency=c(TrueHetFiltAlleleFreq$AlleleFreq, TrueHetFiltAlleleFreq$NullAltFiltAlleleFreq, TrueHetFiltAlleleFreq$SomaticAlleleFreq))
HistogramHysteria$Estimate=factor(HistogramHysteria$Estimate, levels=c("Germline", "Est-Germline", "Est-Somatic"))
Legend=data.frame(SNV=c("Germline", "Est-Germline", "Est-Somatic"))
ggplot(HistogramHysteria, aes(x=AlleleFrequency, fill=Estimate, color=Estimate))+geom_histogram(binwidth=0.01, aes(y=after_stat(density)), position="identity")+labs(x="Alternate Allele Frequency", y="SNVs (%)")+theme(text=element_text(size=14), axis.text.x=element_text(size=8), strip.text.x=element_text(face="bold"), legend.title=element_blank(), legend.position=c(0.86,0.84))+scale_color_manual(values=c("Germline"="black", "Est-Germline"="red", "Est-Somatic"="darkgreen"))+scale_fill_manual(values=c("Germline"="black", "Est-Germline"="NA", "Est-Somatic"="NA"))
ggsave("AllFiltAlleleFreqFullHistogramLP.png", plot = last_plot(), device = png(), path = "C:/Users/mjuswilc/OneDrive - tu-dortmund.de/Documents/TU-Dortmund/GreatTits/Projects/Deconvolution/UltimateDeconvolution/HeterozygoteSimulation/Analyses/Images", scale = 1, width = 7, height = 5, units = c("in"), dpi=300, limitsize = TRUE)
ggplot(HistogramHysteria, aes(x=AlleleFrequency, fill=Estimate, color=Estimate))+geom_histogram(binwidth=0.01, aes(y=after_stat(density)), position="identity")+labs(x="Alternate Allele Frequency", y="SNVs (%)")+theme(text=element_text(size=14), axis.text.x=element_text(size=8), strip.text.x=element_text(face="bold"), legend.title=element_blank())+scale_color_manual(values=c("Germline"="black", "Est-Germline"="red", "Est-Somatic"="darkgreen"))+scale_fill_manual(values=c("Germline"="black", "Est-Germline"="NA", "Est-Somatic"="NA"))
ggsave("AllFiltAlleleFreqFullHistogramFL.png", plot = last_plot(), device = png(), path = "C:/Users/mjuswilc/OneDrive - tu-dortmund.de/Documents/TU-Dortmund/GreatTits/Projects/Deconvolution/UltimateDeconvolution/HeterozygoteSimulation/Analyses/Images", scale = 1, width = 7, height = 5, units = c("in"), dpi=300, limitsize = TRUE)
